
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Random;
import javax.swing.JTextField;
import java.lang.Double;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sarah and Kripa
 */
public class AddEmployeeJFrame extends javax.swing.JFrame {

    String fName = "";
    String lName = "";
    String empNum = "";
    String deductRate = "";
    
    String yearlySalary = "";
    
    String hourlyWage = "";
    String hoursPerWeek = "";
    String weeksPerYear = "";
    
    /**
     * Creates new form AddEmployeeJFrame
     */
    public AddEmployeeJFrame() {
        initComponents();
       
    }
    
    private MyHashTable mainHT;
    
    public void setMainHT(MyHashTable refvalForHT) {
        mainHT = refvalForHT;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RadioFPTEbuttonGroup1 = new javax.swing.ButtonGroup();
        MainADDtitle = new javax.swing.JLabel();
        IntroLabel = new javax.swing.JLabel();
        EMPtypeLabel = new javax.swing.JLabel();
        CANCELADDjButton1 = new javax.swing.JButton();
        FNameLabel = new javax.swing.JLabel();
        FirstNamejTextField = new javax.swing.JTextField();
        LNameLabel = new javax.swing.JLabel();
        LastNamejTextField = new javax.swing.JTextField();
        EMPnumLabel = new javax.swing.JLabel();
        EMPnumField = new javax.swing.JTextField();
        ADDButton = new javax.swing.JButton();
        GenerateNUMButton = new javax.swing.JButton();
        FTEradButton = new javax.swing.JRadioButton();
        PTEradButton = new javax.swing.JRadioButton();
        SalaryInfoLabel = new javax.swing.JLabel();
        HourlyWageLabel = new javax.swing.JLabel();
        HoursPerWeekLabel = new javax.swing.JLabel();
        WeeksPerYearLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        HoursTField = new javax.swing.JTextField();
        HoursWeekTField = new javax.swing.JTextField();
        WeeksTField = new javax.swing.JTextField();
        TotalNETLabel = new javax.swing.JLabel();
        TotalNETTField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        DDRate = new javax.swing.JLabel();
        RateField = new javax.swing.JTextField();
        CLEARbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Employee");
        setMinimumSize(new java.awt.Dimension(860, 730));
        setPreferredSize(new java.awt.Dimension(860, 730));
        setResizable(false);

        MainADDtitle.setFont(new java.awt.Font("URW Gothic L", 1, 25)); // NOI18N
        MainADDtitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MainADDtitle.setText("ADD AN EMPLOYEE");
        MainADDtitle.setToolTipText("");
        MainADDtitle.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        MainADDtitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        IntroLabel.setFont(new java.awt.Font("Ubuntu", 1, 22)); // NOI18N
        IntroLabel.setText("Enter the required information below:");

        EMPtypeLabel.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        EMPtypeLabel.setText("Employee Type:");

        CANCELADDjButton1.setBackground(new java.awt.Color(230, 62, 62));
        CANCELADDjButton1.setFont(new java.awt.Font("URW Gothic L", 1, 20)); // NOI18N
        CANCELADDjButton1.setText("CANCEL");
        CANCELADDjButton1.setToolTipText("CANCEL this operation, nothing will get saved");
        CANCELADDjButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CANCELADDjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CANCELADDjButton1ActionPerformed(evt);
            }
        });

        FNameLabel.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        FNameLabel.setText("First Name:");

        FirstNamejTextField.setFont(new java.awt.Font("URW Gothic L", 0, 18)); // NOI18N
        FirstNamejTextField.setText("First Name...");
        FirstNamejTextField.setToolTipText("Enter the Employee's First Name");
        FirstNamejTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstNamejTextFieldActionPerformed(evt);
            }
        });

        LNameLabel.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        LNameLabel.setText("Last Name:");
        LNameLabel.setToolTipText("");

        LastNamejTextField.setFont(new java.awt.Font("URW Gothic L", 0, 18)); // NOI18N
        LastNamejTextField.setText("Last Name...");
        LastNamejTextField.setToolTipText("Enter The Employee's Last Name");
        LastNamejTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastNamejTextFieldActionPerformed(evt);
            }
        });

        EMPnumLabel.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        EMPnumLabel.setText("Employee Number:");

        EMPnumField.setEditable(false);
        EMPnumField.setFont(new java.awt.Font("URW Gothic L", 0, 18)); // NOI18N
        EMPnumField.setToolTipText("Random Unique Employee Number, CAN'T be changed");
        EMPnumField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EMPnumFieldActionPerformed(evt);
            }
        });

        ADDButton.setBackground(new java.awt.Color(26, 184, 68));
        ADDButton.setFont(new java.awt.Font("URW Gothic L", 1, 20)); // NOI18N
        ADDButton.setText("ADD");
        ADDButton.setToolTipText("Add this employee to the database");
        ADDButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ADDButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ADDButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADDButtonActionPerformed(evt);
            }
        });

        GenerateNUMButton.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        GenerateNUMButton.setText("Generate Number");
        GenerateNUMButton.setToolTipText("Click to generate an Employee Number");
        GenerateNUMButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GenerateNUMButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerateNUMButtonActionPerformed(evt);
            }
        });

        RadioFPTEbuttonGroup1.add(FTEradButton);
        FTEradButton.setFont(new java.awt.Font("URW Gothic L", 0, 18)); // NOI18N
        FTEradButton.setText("Full Time");
        FTEradButton.setToolTipText("Select this for a full time employee");
        FTEradButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FTEradButtonActionPerformed(evt);
            }
        });

        RadioFPTEbuttonGroup1.add(PTEradButton);
        PTEradButton.setFont(new java.awt.Font("URW Gothic L", 0, 18)); // NOI18N
        PTEradButton.setText("Part Time");
        PTEradButton.setToolTipText("Select this for a part time employee");
        PTEradButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PTEradButtonActionPerformed(evt);
            }
        });

        SalaryInfoLabel.setFont(new java.awt.Font("Ubuntu", 1, 22)); // NOI18N
        SalaryInfoLabel.setText("Salary Info: ");

        HourlyWageLabel.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        HourlyWageLabel.setText("Hourly Wage:");

        HoursPerWeekLabel.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        HoursPerWeekLabel.setText("Hours per week:");

        WeeksPerYearLabel.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        WeeksPerYearLabel.setText("Weeks per year:");

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N

        HoursTField.setFont(new java.awt.Font("URW Gothic L", 0, 18)); // NOI18N
        HoursTField.setText("0.00");
        HoursTField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HoursTFieldActionPerformed(evt);
            }
        });

        HoursWeekTField.setFont(new java.awt.Font("URW Gothic L", 0, 18)); // NOI18N
        HoursWeekTField.setText("0.00");
        HoursWeekTField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HoursWeekTFieldActionPerformed(evt);
            }
        });

        WeeksTField.setFont(new java.awt.Font("URW Gothic L", 0, 18)); // NOI18N
        WeeksTField.setText("0.00");
        WeeksTField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WeeksTFieldActionPerformed(evt);
            }
        });

        TotalNETLabel.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        TotalNETLabel.setText("Yearly Salary");
        TotalNETLabel.setToolTipText("");

        TotalNETTField.setFont(new java.awt.Font("URW Gothic L", 0, 18)); // NOI18N
        TotalNETTField.setText("0.00");
        TotalNETTField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalNETTFieldActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(230, 255, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("SansSerif", 0, 17)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(80, 80, 70));
        jTextArea1.setRows(5);
        jTextArea1.setText("                             ***** NOTE *****                           \nThe appropriate salary info input fields will be \navailable based on the  \"Employee Type\" selection.\n\n- If \"Full Time\" is selected, \"Yearly \nSalary\" will be enabled, other fields will be disabled\n\n-If \"Part Time\" is selected, \"Hourly Wage\", \"Hours \nper week\" and \"Weeks per year\" will be enabled,\nother fields will be disabled.\n");
        jScrollPane1.setViewportView(jTextArea1);

        DDRate.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        DDRate.setText("Deduction Rate:");

        RateField.setFont(new java.awt.Font("URW Gothic L", 0, 18)); // NOI18N
        RateField.setText("0.00");
        RateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RateFieldActionPerformed(evt);
            }
        });

        CLEARbutton.setFont(new java.awt.Font("URW Gothic L", 0, 20)); // NOI18N
        CLEARbutton.setText("CLEAR");
        CLEARbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CLEARbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLEARbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addComponent(MainADDtitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(206, 206, 206))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(IntroLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(55, 55, 55))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(EMPnumLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(FNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(LNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(FirstNamejTextField)
                                            .addComponent(LastNamejTextField)
                                            .addComponent(EMPnumField, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(EMPtypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(41, 41, 41)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(PTEradButton)
                                            .addComponent(FTEradButton))))
                                .addGap(47, 47, 47)
                                .addComponent(GenerateNUMButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(DDRate, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(RateField, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(554, Short.MAX_VALUE)
                .addComponent(CLEARbutton)
                .addGap(18, 18, 18)
                .addComponent(ADDButton)
                .addGap(18, 18, 18)
                .addComponent(CANCELADDjButton1)
                .addGap(25, 25, 25))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SalaryInfoLabel)
                            .addComponent(HourlyWageLabel))
                        .addGap(180, 180, 180)
                        .addComponent(TotalNETLabel)
                        .addGap(18, 18, 18)
                        .addComponent(TotalNETTField, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(HoursTField, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(HoursPerWeekLabel)
                                        .addGap(27, 27, 27))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(WeeksPerYearLabel)
                                        .addGap(31, 31, 31)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(WeeksTField)
                                    .addComponent(HoursWeekTField, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainADDtitle, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IntroLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EMPnumLabel)
                    .addComponent(EMPnumField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GenerateNUMButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FirstNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LNameLabel)
                    .addComponent(LastNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(EMPtypeLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(FTEradButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PTEradButton)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DDRate)
                    .addComponent(RateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SalaryInfoLabel)
                    .addComponent(TotalNETLabel)
                    .addComponent(TotalNETTField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(HourlyWageLabel)
                            .addComponent(HoursTField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(HoursPerWeekLabel)
                            .addComponent(HoursWeekTField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(WeeksTField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(WeeksPerYearLabel)))
                    .addComponent(jScrollPane1))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ADDButton)
                    .addComponent(CANCELADDjButton1)
                    .addComponent(CLEARbutton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CANCELADDjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CANCELADDjButton1ActionPerformed
        // TODO add your handling code here:
        super.dispose();
    }//GEN-LAST:event_CANCELADDjButton1ActionPerformed

    private void FirstNamejTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstNamejTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstNamejTextFieldActionPerformed

    private void LastNamejTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastNamejTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LastNamejTextFieldActionPerformed

    private void EMPnumFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EMPnumFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EMPnumFieldActionPerformed

    private void ADDButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADDButtonActionPerformed
        // TODO add your handling code here:
            
        //First Name stuff
        String fName = FirstNamejTextField.getText();
        //System.out.println("The first name is:"+ fName);
        
        //Last name stuff
        String lName = LastNamejTextField.getText();
        
        //Employee Number stuff
        String empNum = EMPnumField.getText();
        int empVal = Integer.parseInt(empNum);
        
        //double deduction rate stuff
        String deductRate = RateField.getText();
        double rateValue = Double.parseDouble(deductRate);
        
        //hourly wage stuff
        String hourlyWage = HoursTField.getText();
        double Hwage = Double.parseDouble(hourlyWage);
        
        //hours per week stuff
        String hoursPerWeek = HoursWeekTField.getText();
        double hours = Double.parseDouble(hoursPerWeek);
        
        //Weeks per year stuff
        String weeksPerYear = WeeksTField.getText();
        double weeks = Double.parseDouble(weeksPerYear);
        
        //Total net stuff
        String yearlySalary = TotalNETTField.getText();
        double salary = Double.parseDouble(yearlySalary);
        

//Now actually adding the employee to the system
       
        if (PTEradButton.isSelected()) {
            PTE thePTE = new PTE (empVal,fName,lName,rateValue,Hwage,hours,weeks) ;
            mainHT.addEmployee(thePTE);  //adding the employee to the hashtable   
        }
        
        if (FTEradButton.isSelected()) {
            FTE theFTE = new FTE (empVal,fName,lName,rateValue,salary);
            mainHT.addEmployee(theFTE); //adding the employee to the hashtable
        }
         
        
        //DISREGARD because the saving command has been moved the the MainJFrame code, and from there it saves the whole hashtable

//After adding to hashtable, we are now saving the employee to the text file
        /*    File file = new File("EMPDATA.txt");
        
            try { 
            FileWriter myWriter = new FileWriter(file);
            for (int i = 0; i < mainHT.buckets.length; i++) {
                for (int j = 0; j < mainHT.buckets[i].size(); j++) {
                    EmployeeInfo theEmp = mainHT.buckets[i].get(j);
                    
                    if(theEmp instanceof PTE){
                        PTE thePTE = (PTE) mainHT.buckets[i].get(j);
                        //PTE theEmpPTE = new PTE (empVal,fName,lName,rateValue,Hwage,hours,weeks) ;
                        myWriter.write("\n");
                        myWriter.write("PTE    (" + Integer.toString(theEmp.getEmpNum()) +", "+ theEmp.getFirstName() + ", " +  theEmp.getLastName() + ", " + Double.toString(theEmp.deductRate) + ", " + Double.toString(thePTE.hourlyWage) + ", " + Double.toString(thePTE.hoursPerWeek) + ", " + Double.toString(thePTE.weeksPerYear) + ")");
                        myWriter.write("\n");
                    //    System.out.println("Successfully wrote PTE to the file!");
                    }
                    
                    else{
                    if (theEmp instanceof FTE){
                        FTE theFTE = (FTE) mainHT.buckets[i].get(j);
                        //FTE theEmpFTE = new FTE (empVal,fName,lName,rateValue,salary);
                        myWriter.write("\n");
                        myWriter.write("FTE    (" + Integer.toString(theEmp.getEmpNum()) +", "+ theEmp.getFirstName() + ", " +  theEmp.getLastName() + ", " + Double.toString(theEmp.deductRate) + ", " + Double.toString(theFTE.yearlySalary)+ ")") ;
                        myWriter.write ("\n");
                    //    System.out.println("Successfully wrote FTE to the file!");
                    }
                    }
                }
            }
            myWriter.close();
        
            }   
            catch (IOException e) {
            System.out.println("AN error occured");
        }            */
   
        //After the saving command, we exit the window
        this.dispose();
    }//GEN-LAST:event_ADDButtonActionPerformed

    private void GenerateNUMButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerateNUMButtonActionPerformed
        // TODO add your handling code here:
        Random num = new Random();
        int randomNum = num.nextInt(900000) + 100000 ;
        String val = String.valueOf(randomNum);
    //  System.out.println(val);
        EMPnumField.setText(val);
        
    }//GEN-LAST:event_GenerateNUMButtonActionPerformed

    private void FTEradButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FTEradButtonActionPerformed
        // TODO add your handling code here:
      
            HourlyWageLabel.setEnabled(false);
            HoursTField.setEnabled(false);
            
            HoursPerWeekLabel.setEnabled(false);
            HoursWeekTField.setEnabled(false);
            
            WeeksPerYearLabel.setEnabled(false);
            WeeksTField.setEnabled(false);
            
            TotalNETLabel.setEnabled(true);
            TotalNETTField.setEnabled(true);
            
    }//GEN-LAST:event_FTEradButtonActionPerformed

    private void PTEradButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PTEradButtonActionPerformed
        // TODO add your handling code here:
        
        TotalNETLabel.setEnabled(false);
        TotalNETTField.setEnabled(false);
        
        HourlyWageLabel.setEnabled(true);
        HoursTField.setEnabled(true);
            
        HoursPerWeekLabel.setEnabled(true);
        HoursWeekTField.setEnabled(true);
            
        WeeksPerYearLabel.setEnabled(true);
        WeeksTField.setEnabled(true);
    }//GEN-LAST:event_PTEradButtonActionPerformed

    private void HoursTFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HoursTFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HoursTFieldActionPerformed

    private void HoursWeekTFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HoursWeekTFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HoursWeekTFieldActionPerformed

    private void WeeksTFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WeeksTFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WeeksTFieldActionPerformed

    private void RateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RateFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RateFieldActionPerformed

    private void TotalNETTFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalNETTFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalNETTFieldActionPerformed

    private void CLEARbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLEARbuttonActionPerformed
        // TODO add your handling code here:
        
        //clearning inputs if they want to delete their info
        EMPnumField.setText("0.00");
        FirstNamejTextField.setText("First Name...  ");
        LastNamejTextField.setText("Last Name... ");
        RateField.setText("0.00");
        HoursTField.setText("0.00");
        HoursWeekTField.setText("0.00");
        WeeksTField.setText("0.00");
        TotalNETTField.setText("0.00");
    }//GEN-LAST:event_CLEARbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddEmployeeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddEmployeeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddEmployeeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddEmployeeJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddEmployeeJFrame().setVisible(true);
            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADDButton;
    private javax.swing.JButton CANCELADDjButton1;
    private javax.swing.JButton CLEARbutton;
    private javax.swing.JLabel DDRate;
    private javax.swing.JTextField EMPnumField;
    private javax.swing.JLabel EMPnumLabel;
    private javax.swing.JLabel EMPtypeLabel;
    private javax.swing.JLabel FNameLabel;
    private javax.swing.JRadioButton FTEradButton;
    private javax.swing.JTextField FirstNamejTextField;
    private javax.swing.JButton GenerateNUMButton;
    private javax.swing.JLabel HourlyWageLabel;
    private javax.swing.JLabel HoursPerWeekLabel;
    private javax.swing.JTextField HoursTField;
    private javax.swing.JTextField HoursWeekTField;
    private javax.swing.JLabel IntroLabel;
    private javax.swing.JLabel LNameLabel;
    private javax.swing.JTextField LastNamejTextField;
    private javax.swing.JLabel MainADDtitle;
    private javax.swing.JRadioButton PTEradButton;
    private javax.swing.ButtonGroup RadioFPTEbuttonGroup1;
    private javax.swing.JTextField RateField;
    private javax.swing.JLabel SalaryInfoLabel;
    private javax.swing.JLabel TotalNETLabel;
    private javax.swing.JTextField TotalNETTField;
    private javax.swing.JLabel WeeksPerYearLabel;
    private javax.swing.JTextField WeeksTField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
