
import java.io.File;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.Scanner;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sarah and Kripa
 */
public class DisplayEmployeesJFrame extends javax.swing.JFrame {

    private MyHashTable mainHT;  // This contains the ref value for theHT of MainJFrame.
        
    public ArrayList<EmployeeInfo>[] buckets;
    private int numInHashTable;
    
    public void setMainHT(MyHashTable refvalForHT) {
        mainHT = refvalForHT;
    } 
    
    /**
     * Creates new form DisplayEmployeesJFrame
     */
    public DisplayEmployeesJFrame() {
        initComponents();

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        displayButton = new javax.swing.JButton();
        Scroll = new javax.swing.JScrollPane();
        TextArea = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Display All Employees");
        setMinimumSize(new java.awt.Dimension(760, 520));
        setResizable(false);

        Title.setFont(new java.awt.Font("URW Gothic L", 1, 25)); // NOI18N
        Title.setText("Here are all the employees recorded in the system:");

        displayButton.setBackground(new java.awt.Color(26, 184, 68));
        displayButton.setFont(new java.awt.Font("URW Gothic L", 1, 20)); // NOI18N
        displayButton.setText("DISPLAY");
        displayButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        displayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayButtonActionPerformed(evt);
            }
        });

        TextArea.setEditable(false);
        TextArea.setBackground(new java.awt.Color(254, 250, 214));
        TextArea.setColumns(20);
        TextArea.setFont(new java.awt.Font("URW Gothic L", 0, 18)); // NOI18N
        TextArea.setRows(8);
        Scroll.setViewportView(TextArea);

        jButton1.setBackground(new java.awt.Color(230, 62, 62));
        jButton1.setFont(new java.awt.Font("URW Gothic L", 1, 20)); // NOI18N
        jButton1.setText("CLOSE");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(281, 281, 281)
                .addComponent(displayButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(61, 61, 61))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Title))
                        .addGap(39, 39, 39))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title)
                .addGap(16, 16, 16)
                .addComponent(displayButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     *
     */
    
    

    private void displayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayButtonActionPerformed
        // TODO add your handling code here:
       
       int numInHT = mainHT.getNumInHashTable();
        if (numInHT > 0) {
        //    String firstString = "Here are the employees:\n";
        //    TextArea.setText(firstString);
           String wholeData0 = "";
           String wholeData1 = "";
            for (int i = 0; i < mainHT.buckets.length; i++) {
                for (int j = 0; j < mainHT.buckets[i].size(); j++) {
                    
                    EmployeeInfo theEmp = mainHT.buckets[i].get(j);
                    
                    
                    if (theEmp instanceof FTE) {
                        FTE theFTE = (FTE) theEmp;
                         wholeData0 = wholeData0 + ("\nEmployee Type: Full Time" +/* "\n" + Integer.toString(theEmp.getEmpNum()) +", "+ theEmp.getFirstName() + ", " +  theEmp.getLastName() + */"\n" + "  Employee number: " + Integer.toString(theEmp.getEmpNum()) + "\n" + "  Full Name (First, Last): " + theEmp.getFirstName() + " " + theEmp.getLastName() + "\n" + "    Yearly salary: $" + Double.toString(theFTE.yearlySalary) + "\n" + "      Net Annual Income: $ " + ((1.0 - ((FTE) theEmp).deductRate) * ((FTE) theEmp).yearlySalary) + "\n" );
                    
                    }
                    if (theEmp instanceof PTE) {
                        PTE thePTE = (PTE) theEmp;
                         wholeData1 = wholeData1 + ("\nEmployee Type: Part Time" + /*"\n" + Integer.toString(theEmp.getEmpNum()) +", "+ theEmp.getFirstName() + ", " +  theEmp.getLastName() + */"\n" + "  Employee number: " + Integer.toString(theEmp.getEmpNum()) + "\n" + "  Full Name (First, Last): " + theEmp.getFirstName() + " " + theEmp.getLastName() + "\n" + "    Hourly wage: $" + Double.toString(thePTE.hourlyWage) + "\n" + "    Hours per week: " + Double.toString(thePTE.hoursPerWeek) + "\n" + "    Weeks per year: " + Double.toString(thePTE.weeksPerYear) + "\n" + "      Net Annual Income: $ " + (1.0 - ((PTE) theEmp).deductRate) * ((PTE) theEmp).hourlyWage * ((PTE) theEmp).hoursPerWeek * ((PTE) theEmp).weeksPerYear + "\n");
                    }
                }
            }
            TextArea.setText(wholeData0 + wholeData1);
        }
        
        else {
            TextArea.setText("There's NOTHING in the Hash Table!");
        }
    }//GEN-LAST:event_displayButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DisplayEmployeesJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DisplayEmployeesJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DisplayEmployeesJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DisplayEmployeesJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DisplayEmployeesJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane Scroll;
    private javax.swing.JTextArea TextArea;
    private javax.swing.JLabel Title;
    private javax.swing.JButton displayButton;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
