/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sarah and Kripa
 */


public class EditEmpJFrame extends javax.swing.JFrame {

    /**
     * Creates new form EditEmpJFrame
     */
        
    public static String empNum = "";
    public static int empVal = 0;
    public static String fName = "";
    public static String lName = "";
    public static String deductRate = "";
    
    public static String yearlySalary = "";
    
    public static String hourlyWage = "";
    public static String hoursPerWeek = "";
    public static String weeksPerYear = "";
    
//    String fName = "";
//   String lName = "";
      
//    int empVal = 0 ;
//   String deductRate = "";
    
//    String yearlySalary = "";
    
//    String hourlyWage = "";
//    String hoursPerWeek = "";
//    String weeksPerYear = "";

    public EditEmpJFrame() {
        initComponents();
    }

    private MyHashTable mainHT;
    
     public MyHashTable getTheHT() {
        return mainHT;
    }
    
    public void setMainHT(MyHashTable refvalForHT) {
        mainHT = refvalForHT;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        REMOVEtitle = new javax.swing.JLabel();
        instructLabel = new javax.swing.JLabel();
        EmpNumLabel = new javax.swing.JLabel();
        EmployeeNumField = new javax.swing.JTextField();
        CANCELbutton = new javax.swing.JButton();
        CONTINUEbutton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        GetInfo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edit Employee: Part1");
        setMinimumSize(new java.awt.Dimension(801, 582));
        setResizable(false);

        REMOVEtitle.setFont(new java.awt.Font("URW Gothic L", 1, 25)); // NOI18N
        REMOVEtitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        REMOVEtitle.setText("EDIT AN EMPLOYEE - Part 1/2");
        REMOVEtitle.setToolTipText("");
        REMOVEtitle.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        REMOVEtitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        instructLabel.setFont(new java.awt.Font("URW Gothic L", 1, 22)); // NOI18N
        instructLabel.setForeground(new java.awt.Color(199, 0, 0));
        instructLabel.setText("To edit an existing employee, please enter a valid employee number:");

        EmpNumLabel.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        EmpNumLabel.setText("Employee Number: ");

        EmployeeNumField.setFont(new java.awt.Font("URW Gothic L", 0, 18)); // NOI18N
        EmployeeNumField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmployeeNumFieldActionPerformed(evt);
            }
        });

        CANCELbutton.setBackground(new java.awt.Color(230, 62, 62));
        CANCELbutton.setFont(new java.awt.Font("URW Gothic L", 1, 20)); // NOI18N
        CANCELbutton.setText("CANCEL");
        CANCELbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CANCELbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CANCELbuttonActionPerformed(evt);
            }
        });

        CONTINUEbutton.setBackground(new java.awt.Color(26, 184, 68));
        CONTINUEbutton.setFont(new java.awt.Font("URW Gothic L", 1, 20)); // NOI18N
        CONTINUEbutton.setText("CONTINUE");
        CONTINUEbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CONTINUEbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CONTINUEbuttonActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(254, 239, 230));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        GetInfo.setFont(new java.awt.Font("URW Gothic L", 0, 20)); // NOI18N
        GetInfo.setText("Get Info");
        GetInfo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GetInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GetInfoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("URW Gothic L", 1, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(50, 62, 168));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Here is the employee's info:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(45, 45, 45)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(EmpNumLabel)
                                .addComponent(EmployeeNumField, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(24, 24, 24)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(REMOVEtitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(instructLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(CONTINUEbutton)
                                    .addGap(18, 18, 18)
                                    .addComponent(CANCELbutton))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 734, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 734, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(GetInfo)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(REMOVEtitle, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(instructLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(EmpNumLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EmployeeNumField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(GetInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CANCELbutton)
                    .addComponent(CONTINUEbutton))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EmployeeNumFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployeeNumFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmployeeNumFieldActionPerformed

    private void CANCELbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CANCELbuttonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_CANCELbuttonActionPerformed

    private void CONTINUEbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CONTINUEbuttonActionPerformed
        // TODO add your handling code here:

        Edit2JFrame openNewWindows = new Edit2JFrame();
        
    //    Edit2JFrame frameOne;
    //    frameOne = new Edit2JFrame(EmployeeNumField.getText());
    //  new Edit2JFrame(empNum).setVisible(true);

    //    empNum = EmployeeNumField.getText();
        openNewWindows.setVisible(true);
        MyHashTable refVal = getTheHT();
        openNewWindows.setMainHT(refVal);
//        EditEmpJFrame.EmployeeNumField.setText(empNum);
    //    System.out.println(empNum);

        
        this.dispose();
    }//GEN-LAST:event_CONTINUEbuttonActionPerformed

    
    private void GetInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GetInfoActionPerformed
        // TODO add your handling code here:
        
         empNum = EmployeeNumField.getText();
         empVal = Integer.parseInt(empNum);
      
        int positionInArrayList = mainHT.searchByEmployeeNumber(empVal);
        
    //    new EditJFrame(int empVal).setVisible(true);

    /*    if( positionInArrayList < 0 ){
            jTextArea1.setText("THIS EMPLOYEE DOESN'T EXIST, Please enter a valid employee number");
    //    NonExistJFrame openNewWindow5 = new NonExistJFrame();
    //    openNewWindow5.setVisible(true);
        }        
        
        else{
            
        }
       */

        if( positionInArrayList < 0 ){
           
            jTextArea1.setText("THIS EMPLOYEE DOES NOT EXIST, please enter a valid employee number");
            
        }
    
    
        else{
        int numInHT = mainHT.getNumInHashTable();
        int targetBucket = mainHT.calcBucket(empVal);
            for (int j = 0; j < mainHT.buckets[targetBucket].size(); j++){
                if (empVal == mainHT.buckets[targetBucket].get(j).getEmpNum()){
            
            EmployeeInfo theEmp = mainHT.buckets[targetBucket].get(j);
        String thePerson = "";
            if (theEmp instanceof FTE) {
                FTE theFTE = (FTE) theEmp;
                 thePerson = ("    Employee Type: FULL TIME" + "\n" + /*Integer.toString(theEmp.getEmpNum()) +", "+ theEmp.getFirstName() + ", " +  theEmp.getLastName() + "\n" + "  Employee number: " + Integer.toString(theEmp.getEmpNum()) + */ "\n" + "    Full Name (First, Last): " + theEmp.getFirstName() + " " + theEmp.getLastName() + "\n" + "    This employee has yearly salary: $" + Double.toString(theFTE.yearlySalary) + "\n" + "    This employee has Net Annual Income: $ " + ((1.0 - ((FTE) theEmp).deductRate) * ((FTE) theEmp).yearlySalary) + "\n" );
            }
            if (theEmp instanceof PTE) {
                PTE thePTE = (PTE) theEmp;
                 thePerson = ("    Employee Type: PART TIME" + "\n" +/* Integer.toString(theEmp.getEmpNum()) +", "+ theEmp.getFirstName() + ", " +  theEmp.getLastName() + "\n" + "  Employee number: " + Integer.toString(theEmp.getEmpNum()) +*/ "\n" + "    Full Name (First, Last): " + theEmp.getFirstName() + " " + theEmp.getLastName() + "\n" + "    This employee has hourly wage: $" + Double.toString(thePTE.hourlyWage) + "\n" + "    This employee has hours per week: " + Double.toString(thePTE.hoursPerWeek) + "\n" + "    This employee has weeks per year: " + Double.toString(thePTE.weeksPerYear) + "\n" + "This employee has Net Annual Income: $ " + (1.0 - ((PTE) theEmp).deductRate) * ((PTE) theEmp).hourlyWage * ((PTE) theEmp).hoursPerWeek * ((PTE) theEmp).weeksPerYear + "\n");
            }
            
            jTextArea1.setText(thePerson);
            
            }
        }
    }
    
    }//GEN-LAST:event_GetInfoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditEmpJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditEmpJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditEmpJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditEmpJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditEmpJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CANCELbutton;
    private javax.swing.JButton CONTINUEbutton;
    private javax.swing.JLabel EmpNumLabel;
    private javax.swing.JTextField EmployeeNumField;
    private javax.swing.JButton GetInfo;
    private javax.swing.JLabel REMOVEtitle;
    private javax.swing.JLabel instructLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
