
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @authors Sarah and Kripa
 */
public class Edit2JFrame extends javax.swing.JFrame {
    /**
     * Creates new form Edit2JFrame
    
     */
    
public EditEmpJFrame empNum;
int empVal = 0;
    
private MyHashTable mainHT;
    
  public MyHashTable getTheHT() {
        return mainHT;
    }
    
    public void setMainHT(MyHashTable refvalForHT) {
        mainHT = refvalForHT;
    }
      

    public Edit2JFrame() {
        initComponents();
        EMPnumField.setText(EditEmpJFrame.empNum);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        IntroLabel = new javax.swing.JLabel();
        EMPnumLabel = new javax.swing.JLabel();
        EMPnumField = new javax.swing.JTextField();
        FirstNamejTextField = new javax.swing.JTextField();
        FNameLabel = new javax.swing.JLabel();
        LNameLabel = new javax.swing.JLabel();
        LastNamejTextField = new javax.swing.JTextField();
        FTEradButton = new javax.swing.JRadioButton();
        PTEradButton = new javax.swing.JRadioButton();
        EMPtypeLabel = new javax.swing.JLabel();
        DDRate = new javax.swing.JLabel();
        RateField = new javax.swing.JTextField();
        HourlyWageLabel = new javax.swing.JLabel();
        HoursTField = new javax.swing.JTextField();
        HoursWeekTField = new javax.swing.JTextField();
        HoursPerWeekLabel = new javax.swing.JLabel();
        WeeksPerYearLabel = new javax.swing.JLabel();
        WeeksTField = new javax.swing.JTextField();
        TotalNETLabel = new javax.swing.JLabel();
        TotalNETTField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        CANCELADDjButton1 = new javax.swing.JButton();
        EDITbutton2 = new javax.swing.JButton();
        SalaryInfoLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        MainADDtitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        GetDefaultButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edit Employee: Part2");
        setResizable(false);

        IntroLabel.setFont(new java.awt.Font("URW Gothic L", 1, 22)); // NOI18N
        IntroLabel.setText("Edit the required information below:");

        EMPnumLabel.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        EMPnumLabel.setText("Employee Number:");

        EMPnumField.setEditable(false);
        EMPnumField.setFont(new java.awt.Font("URW Gothic L", 0, 18)); // NOI18N
        EMPnumField.setToolTipText("Random Unique Employee Number, CAN'T be changed");
        EMPnumField.setSelectionColor(java.awt.Color.orange);
        EMPnumField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EMPnumFieldActionPerformed(evt);
            }
        });

        FirstNamejTextField.setFont(new java.awt.Font("URW Gothic L", 0, 18)); // NOI18N
        FirstNamejTextField.setText("First Name...");
        FirstNamejTextField.setToolTipText("Enter the Employee's First Name");
        FirstNamejTextField.setSelectionColor(java.awt.Color.orange);
        FirstNamejTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstNamejTextFieldActionPerformed(evt);
            }
        });

        FNameLabel.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        FNameLabel.setText("First Name:");

        LNameLabel.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        LNameLabel.setText("Last Name:");
        LNameLabel.setToolTipText("");

        LastNamejTextField.setFont(new java.awt.Font("URW Gothic L", 0, 18)); // NOI18N
        LastNamejTextField.setText("Last Name...");
        LastNamejTextField.setToolTipText("Enter The Employee's Last Name");
        LastNamejTextField.setSelectionColor(java.awt.Color.orange);
        LastNamejTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastNamejTextFieldActionPerformed(evt);
            }
        });

        buttonGroup1.add(FTEradButton);
        FTEradButton.setFont(new java.awt.Font("URW Gothic L", 0, 18)); // NOI18N
        FTEradButton.setText("Full TIme");
        FTEradButton.setToolTipText("Select this for a full time employee");
        FTEradButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FTEradButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(PTEradButton);
        PTEradButton.setFont(new java.awt.Font("URW Gothic L", 0, 18)); // NOI18N
        PTEradButton.setText("Part Time");
        PTEradButton.setToolTipText("Select this for a part time employee");
        PTEradButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PTEradButtonActionPerformed(evt);
            }
        });

        EMPtypeLabel.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        EMPtypeLabel.setText("Employee Type:");

        DDRate.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        DDRate.setText("Deduction Rate:");

        RateField.setFont(new java.awt.Font("URW Gothic L", 0, 18)); // NOI18N
        RateField.setText("0.00");
        RateField.setSelectionColor(java.awt.Color.orange);
        RateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RateFieldActionPerformed(evt);
            }
        });

        HourlyWageLabel.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        HourlyWageLabel.setText("Hourly Wage:");

        HoursTField.setFont(new java.awt.Font("URW Gothic L", 0, 18)); // NOI18N
        HoursTField.setText("0.00");
        HoursTField.setSelectionColor(java.awt.Color.orange);
        HoursTField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HoursTFieldActionPerformed(evt);
            }
        });

        HoursWeekTField.setFont(new java.awt.Font("URW Gothic L", 0, 18)); // NOI18N
        HoursWeekTField.setText("0.00");
        HoursWeekTField.setSelectionColor(java.awt.Color.orange);
        HoursWeekTField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HoursWeekTFieldActionPerformed(evt);
            }
        });

        HoursPerWeekLabel.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        HoursPerWeekLabel.setText("Hours per week:");

        WeeksPerYearLabel.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        WeeksPerYearLabel.setText("Weeks per year:");

        WeeksTField.setFont(new java.awt.Font("URW Gothic L", 0, 18)); // NOI18N
        WeeksTField.setText("0.00");
        WeeksTField.setSelectionColor(java.awt.Color.orange);
        WeeksTField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WeeksTFieldActionPerformed(evt);
            }
        });

        TotalNETLabel.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        TotalNETLabel.setText("Yearly Salary:");
        TotalNETLabel.setToolTipText("");

        TotalNETTField.setFont(new java.awt.Font("URW Gothic L", 0, 18)); // NOI18N
        TotalNETTField.setText("0.00");
        TotalNETTField.setSelectionColor(java.awt.Color.orange);
        TotalNETTField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalNETTFieldActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(230, 255, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("SansSerif", 0, 17)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(80, 80, 70));
        jTextArea1.setRows(5);
        jTextArea1.setText("PRESS \"GET PREVIOUS INFO\" button to get \nmore information\n");
        jTextArea1.setSelectionColor(java.awt.Color.orange);
        jScrollPane1.setViewportView(jTextArea1);

        CANCELADDjButton1.setBackground(new java.awt.Color(230, 62, 62));
        CANCELADDjButton1.setFont(new java.awt.Font("URW Gothic L", 1, 20)); // NOI18N
        CANCELADDjButton1.setText("CANCEL");
        CANCELADDjButton1.setToolTipText("CANCEL this operation, nothing will get saved");
        CANCELADDjButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CANCELADDjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CANCELADDjButton1ActionPerformed(evt);
            }
        });

        EDITbutton2.setBackground(new java.awt.Color(26, 184, 68));
        EDITbutton2.setFont(new java.awt.Font("URW Gothic L", 1, 20)); // NOI18N
        EDITbutton2.setText("EDIT");
        EDITbutton2.setToolTipText("Add this employee to the database");
        EDITbutton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EDITbutton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        EDITbutton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EDITbutton2ActionPerformed(evt);
            }
        });

        SalaryInfoLabel.setFont(new java.awt.Font("URW Gothic L", 1, 22)); // NOI18N
        SalaryInfoLabel.setText("Salary Info: ");

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setFont(new java.awt.Font("Ubuntu", 1, 36)); // NOI18N

        MainADDtitle.setFont(new java.awt.Font("URW Gothic L", 1, 24)); // NOI18N
        MainADDtitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MainADDtitle.setText("EDIT AN EMPLOYEE - Part 2/2");
        MainADDtitle.setToolTipText("");
        MainADDtitle.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        MainADDtitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel1.setText("NOTE: Employee Number cannot be edited");

        GetDefaultButton.setFont(new java.awt.Font("URW Gothic L", 1, 20)); // NOI18N
        GetDefaultButton.setText("GET PREVIOUS INFO");
        GetDefaultButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GetDefaultButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GetDefaultButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(323, 323, 323)
                .addComponent(GetDefaultButton)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(SalaryInfoLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(IntroLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MainADDtitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator1))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(HourlyWageLabel)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(HoursTField, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(WeeksPerYearLabel)
                                            .addGap(31, 31, 31))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(HoursPerWeekLabel)
                                            .addGap(27, 27, 27)))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(WeeksTField)
                                        .addComponent(HoursWeekTField, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TotalNETLabel)
                        .addGap(18, 18, 18)
                        .addComponent(TotalNETTField, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(160, 160, 160))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(EMPnumLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(FNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(FirstNamejTextField)
                                    .addComponent(LastNamejTextField)
                                    .addComponent(EMPnumField, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(EMPtypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(PTEradButton)
                                    .addComponent(FTEradButton)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(DDRate, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(RateField, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                                .addGap(53, 53, 53))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(55, Short.MAX_VALUE))))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(665, 665, 665)
                    .addComponent(EDITbutton2)
                    .addGap(18, 18, 18)
                    .addComponent(CANCELADDjButton1)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MainADDtitle, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GetDefaultButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(IntroLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EMPnumLabel)
                    .addComponent(EMPnumField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(FNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FirstNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LNameLabel)
                            .addComponent(LastNamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(EMPtypeLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(FTEradButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(PTEradButton)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DDRate)
                            .addComponent(RateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SalaryInfoLabel)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HourlyWageLabel)
                    .addComponent(HoursTField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TotalNETLabel)
                    .addComponent(TotalNETTField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HoursPerWeekLabel)
                    .addComponent(HoursWeekTField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WeeksTField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WeeksPerYearLabel))
                .addGap(73, 73, 73))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap(701, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(EDITbutton2)
                        .addComponent(CANCELADDjButton1))
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EMPnumFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EMPnumFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EMPnumFieldActionPerformed

    private void FirstNamejTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstNamejTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstNamejTextFieldActionPerformed

    private void LastNamejTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastNamejTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LastNamejTextFieldActionPerformed

    private void FTEradButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FTEradButtonActionPerformed
        // TODO add your handling code here:

        HourlyWageLabel.setEnabled(false);
        HoursTField.setEnabled(false);

        HoursPerWeekLabel.setEnabled(false);
        HoursWeekTField.setEnabled(false);

        WeeksPerYearLabel.setEnabled(false);
        WeeksTField.setEnabled(false);

        TotalNETLabel.setEnabled(true);
        TotalNETTField.setEnabled(true);

    }//GEN-LAST:event_FTEradButtonActionPerformed

    private void PTEradButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PTEradButtonActionPerformed
        // TODO add your handling code here:

        TotalNETLabel.setEnabled(false);
        TotalNETTField.setEnabled(false);

        HourlyWageLabel.setEnabled(true);
        HoursTField.setEnabled(true);

        HoursPerWeekLabel.setEnabled(true);
        HoursWeekTField.setEnabled(true);

        WeeksPerYearLabel.setEnabled(true);
        WeeksTField.setEnabled(true);
    }//GEN-LAST:event_PTEradButtonActionPerformed

    private void RateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RateFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RateFieldActionPerformed

    private void HoursTFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HoursTFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HoursTFieldActionPerformed

    private void HoursWeekTFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HoursWeekTFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HoursWeekTFieldActionPerformed

    private void WeeksTFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WeeksTFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_WeeksTFieldActionPerformed

    private void TotalNETTFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalNETTFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalNETTFieldActionPerformed

    private void CANCELADDjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CANCELADDjButton1ActionPerformed
        // TODO add your handling code here:
        super.dispose();
    }//GEN-LAST:event_CANCELADDjButton1ActionPerformed

    private void EDITbutton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EDITbutton2ActionPerformed
        // TODO add your handling code here:
        
        //First Name stuff
        String fName = FirstNamejTextField.getText();
        //System.out.println("The first name is:"+ fName);

        //Last name stuff
        String lName = LastNamejTextField.getText();

        //Employee Number stuff
        String empNum = EMPnumField.getText();
        int empVal1 = Integer.parseInt(empNum);

        //double deduction rate stuff
        String deductRate = RateField.getText();
        double rateValue1 = Double.parseDouble(deductRate);

        //hourly wage stuff
        String hourlyWage = HoursTField.getText();
        double hWage1 = Double.parseDouble(hourlyWage);

        //hours per week stuff
        String hoursPerWeek = HoursWeekTField.getText();
        double hours1 = Double.parseDouble(hoursPerWeek);

        //Weeks per year stuff
        String weeksPerYear = WeeksTField.getText();
        double weeks1 = Double.parseDouble(weeksPerYear);

        //Total net stuff
        String yearlySalary = TotalNETTField.getText();
        double salary1 = Double.parseDouble(yearlySalary);

        //First removing the old employee, so we can add the updated one
          mainHT.removeEmployee(empVal1);
        System.out.println(empVal1);
        
        //Now actually adding the updated employee to the system

        if (PTEradButton.isSelected()) {
            PTE thePTE = new PTE (empVal1,fName,lName,rateValue1,hWage1,hours1,weeks1) ;
            mainHT.addEmployee(thePTE);  //adding the employee to the hashtable
        }

        if (FTEradButton.isSelected()) {
            FTE theFTE = new FTE (empVal1,fName,lName,rateValue1,salary1);
            mainHT.addEmployee(theFTE); //adding the employee to the hashtable
        }

        //After the saving command, we exit the window
        this.dispose();
    }//GEN-LAST:event_EDITbutton2ActionPerformed

    private void GetDefaultButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GetDefaultButtonActionPerformed
        // TODO add your handling code here:
        
    //    EMPnumField.setText(getEmpNum());
    String empVal2 = EMPnumField.getText();
    int empRealNum = Integer.parseInt(empVal2);
    int positionInArrayList = mainHT.searchByEmployeeNumber(empRealNum);
       
        if( positionInArrayList < 0 ){
           
            jTextArea1.setText("THIS EMPLOYEE DOES NOT EXIST, please enter a valid employee number");
            
        }
    
    
        else{
        int numInHT = mainHT.getNumInHashTable();
        int targetBucket = mainHT.calcBucket(empRealNum);
            for (int j = 0; j < mainHT.buckets[targetBucket].size(); j++){
                if (empRealNum == mainHT.buckets[targetBucket].get(j).getEmpNum()){
            
            EmployeeInfo theEmp = mainHT.buckets[targetBucket].get(j);
        String thePerson = "";
            if (theEmp instanceof FTE) {
                FTE theFTE = (FTE) theEmp;
                 thePerson = ("DEFAULT INFO FOR THIS EMPLOYEE\nEmployee Type: Full Time" + "\n" + Integer.toString(theEmp.getEmpNum()) +", "+theEmp.getFirstName() + ", " +  theEmp.getLastName() + "\n" + "  Employee number: " + Integer.toString(theEmp.getEmpNum()) + "\n" + "  Full Name (First,Last): " + theEmp.getFirstName() + " " + theEmp.getLastName() + "\n" + "    This employee has yearly salary: $" + Double.toString(theFTE.yearlySalary) + "\n" + "    This employee has Net Annual Income: $ " + ((1.0 - ((FTE) theEmp).deductRate) * ((FTE) theEmp).yearlySalary) + "\n" );
            
                 FirstNamejTextField.setText(theEmp.getFirstName());
                 LastNamejTextField.setText(theEmp.getLastName());
                 FTEradButton.setSelected(rootPaneCheckingEnabled);
                 
                    HoursTField.setText("0.00");
                    HourlyWageLabel.setEnabled(false);
                    HoursTField.setEnabled(false);

                    HoursWeekTField.setText("0.00");
                    HoursPerWeekLabel.setEnabled(false);
                    HoursWeekTField.setEnabled(false);

                    WeeksTField.setText("0.00");
                    WeeksPerYearLabel.setEnabled(false);
                    WeeksTField.setEnabled(false);

                    TotalNETLabel.setEnabled(true);
                    TotalNETTField.setEnabled(true);
                    
                    double dRate = theEmp.getDeductRate();
                    String dRateReal = Double.toString(dRate);
                    RateField.setText(dRateReal);
                    
                    double net = ((FTE) theEmp).yearlySalary;
                    String salary = Double.toString(net);
                    TotalNETTField.setText(salary);
                    
            
            }
            
            if (theEmp instanceof PTE) {
                PTE thePTE = (PTE) theEmp;
                 thePerson = ("DEFAULT INFO FOR THIS EMPLOYEE\nEmployee Type: Part Time" + "\n" + Integer.toString(theEmp.getEmpNum()) +", "+ theEmp.getFirstName() + ", " +  theEmp.getLastName() + "\n" + "  Employee number: " + Integer.toString(theEmp.getEmpNum()) + "\n" + "  Full Name (First,Last): " + theEmp.getFirstName() + " " + theEmp.getLastName() + "\n" + "    This employee has hourly wage: $" + Double.toString(thePTE.hourlyWage) + "\n" + "    This employee has hours per week: " + Double.toString(thePTE.hoursPerWeek) + "\n" + "    This employee has weeks per year: " + Double.toString(thePTE.weeksPerYear) + "\n" + "This employee has Net Annual Income: $ " + (1.0 - ((PTE) theEmp).deductRate) * ((PTE) theEmp).hourlyWage * ((PTE) theEmp).hoursPerWeek * ((PTE) theEmp).weeksPerYear + "\n");
            
                FirstNamejTextField.setText(theEmp.getFirstName());
                LastNamejTextField.setText(theEmp.getLastName());
                PTEradButton.setSelected(rootPaneCheckingEnabled);
                
                    TotalNETTField.setText("0.00");
                    TotalNETLabel.setEnabled(false);
                    TotalNETTField.setEnabled(false);

                    HourlyWageLabel.setEnabled(true);
                    HoursTField.setEnabled(true);

                    HoursPerWeekLabel.setEnabled(true);
                    HoursWeekTField.setEnabled(true);

                    WeeksPerYearLabel.setEnabled(true);
                    WeeksTField.setEnabled(true);

                    double dRate = theEmp.getDeductRate();
                    String dRateReal = Double.toString(dRate);
                    RateField.setText(dRateReal);
                    
                    double hours = ((PTE) theEmp).getHourlyWage();
                    String wage = Double.toString(hours);
                    HoursTField.setText(wage);
                    
                    double hoursPerWeek = ((PTE) theEmp).getHoursPerWeek();
                    String hoursWeekly = Double.toString(hoursPerWeek);
                    HoursWeekTField.setText(hoursWeekly);
                    
                    double totalWeeks = ((PTE) theEmp).getWeeksPerYear();
                    String weeks = Double.toString(totalWeeks);
                    WeeksTField.setText(weeks);
                    
            }
            
            jTextArea1.setText(thePerson);
            
            }
        }
    }
    
    
    
    }//GEN-LAST:event_GetDefaultButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Edit2JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Edit2JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Edit2JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Edit2JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Edit2JFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CANCELADDjButton1;
    private javax.swing.JLabel DDRate;
    private javax.swing.JButton EDITbutton2;
    private javax.swing.JTextField EMPnumField;
    private javax.swing.JLabel EMPnumLabel;
    private javax.swing.JLabel EMPtypeLabel;
    private javax.swing.JLabel FNameLabel;
    private javax.swing.JRadioButton FTEradButton;
    private javax.swing.JTextField FirstNamejTextField;
    private javax.swing.JButton GetDefaultButton;
    private javax.swing.JLabel HourlyWageLabel;
    private javax.swing.JLabel HoursPerWeekLabel;
    private javax.swing.JTextField HoursTField;
    private javax.swing.JTextField HoursWeekTField;
    private javax.swing.JLabel IntroLabel;
    private javax.swing.JLabel LNameLabel;
    private javax.swing.JTextField LastNamejTextField;
    private javax.swing.JLabel MainADDtitle;
    private javax.swing.JRadioButton PTEradButton;
    private javax.swing.JTextField RateField;
    private javax.swing.JLabel SalaryInfoLabel;
    private javax.swing.JLabel TotalNETLabel;
    private javax.swing.JTextField TotalNETTField;
    private javax.swing.JLabel WeeksPerYearLabel;
    private javax.swing.JTextField WeeksTField;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
