
import java.awt.Color;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.io.File;  // Import the File class
import java.io.FileNotFoundException;  // Import this class to handle errors
import java.util.ArrayList;
import java.util.Scanner; // Import the Scanner class to read text files


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sarah and Kripa
 */
public class MainJFrame extends javax.swing.JFrame {
    
    // ATTRIBUTES
    private MyHashTable theHT;
    
    // CONSTRUCTORS
    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        
        theHT = new MyHashTable(10);
        
        
    }
    
    
    // METHODS   
    
    public MyHashTable getTheHT() {
        return theHT;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ADDemployee = new javax.swing.JButton();
        Seperate = new javax.swing.JButton();
        MainTitle = new javax.swing.JLabel();
        DisplayEmployees = new javax.swing.JButton();
        SAVEbutton = new javax.swing.JButton();
        LOADbutton = new javax.swing.JButton();
        REMOVEemployee = new javax.swing.JButton();
        EDITbutton = new javax.swing.JButton();
        GETINFObutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("EMS Main/Home");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(600, 476));
        setName("MainFrame"); // NOI18N
        setResizable(false);

        ADDemployee.setFont(new java.awt.Font("URW Gothic L", 1, 22)); // NOI18N
        ADDemployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/add.png"))); // NOI18N
        ADDemployee.setText("Add Employee");
        ADDemployee.setToolTipText("Click to proceed to ADDING an employee");
        ADDemployee.setActionCommand("AddEmployee");
        ADDemployee.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ADDemployee.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ADDemployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADDemployeeActionPerformed(evt);
            }
        });

        Seperate.setFont(new java.awt.Font("URW Gothic L", 1, 22)); // NOI18N
        Seperate.setText("# of Employees");
        Seperate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Seperate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeperateActionPerformed(evt);
            }
        });

        MainTitle.setFont(new java.awt.Font("URW Gothic L", 1, 36)); // NOI18N
        MainTitle.setForeground(new java.awt.Color(153, 153, 255));
        MainTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MainTitle.setText("Welcome to the ICS4U0 EMS");
        MainTitle.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        DisplayEmployees.setFont(new java.awt.Font("URW Gothic L", 1, 22)); // NOI18N
        DisplayEmployees.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/friends.png"))); // NOI18N
        DisplayEmployees.setText("Display Employees");
        DisplayEmployees.setToolTipText("Click to proceed to DISPLAYING all the employees");
        DisplayEmployees.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DisplayEmployees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayEmployeesActionPerformed(evt);
            }
        });

        SAVEbutton.setFont(new java.awt.Font("URW Gothic L", 1, 22)); // NOI18N
        SAVEbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/save.png"))); // NOI18N
        SAVEbutton.setText("SAVE");
        SAVEbutton.setToolTipText("CLick to SAVE the employee data");
        SAVEbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SAVEbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAVEbuttonActionPerformed(evt);
            }
        });

        LOADbutton.setFont(new java.awt.Font("URW Gothic L", 1, 22)); // NOI18N
        LOADbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/load.png"))); // NOI18N
        LOADbutton.setText("LOAD");
        LOADbutton.setToolTipText("Click to LOAD the EmployeeData");
        LOADbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LOADbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOADbuttonActionPerformed(evt);
            }
        });

        REMOVEemployee.setFont(new java.awt.Font("URW Gothic L", 1, 22)); // NOI18N
        REMOVEemployee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/remove.png"))); // NOI18N
        REMOVEemployee.setText("Remove Employee");
        REMOVEemployee.setToolTipText("Click to proceed to REMOVING an employee");
        REMOVEemployee.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        REMOVEemployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REMOVEemployeeActionPerformed(evt);
            }
        });

        EDITbutton.setFont(new java.awt.Font("URW Gothic L", 1, 22)); // NOI18N
        EDITbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/edit.png"))); // NOI18N
        EDITbutton.setText("Edit An Employee");
        EDITbutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EDITbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EDITbuttonActionPerformed(evt);
            }
        });

        GETINFObutton.setFont(new java.awt.Font("URW Gothic L", 1, 22)); // NOI18N
        GETINFObutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/search.png"))); // NOI18N
        GETINFObutton.setText("Get Info On Employee");
        GETINFObutton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GETINFObutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GETINFObuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(REMOVEemployee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(EDITbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ADDemployee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DisplayEmployees, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(Seperate)
                                .addGap(37, 37, 37))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(SAVEbutton)
                                    .addComponent(LOADbutton))
                                .addGap(95, 95, 95))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(GETINFObutton)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(MainTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(MainTitle)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ADDemployee, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SAVEbutton))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DisplayEmployees)
                    .addComponent(LOADbutton))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(REMOVEemployee)
                    .addComponent(Seperate))
                .addGap(39, 39, 39)
                .addComponent(EDITbutton)
                .addGap(31, 31, 31)
                .addComponent(GETINFObutton)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("MainJFrame EMS");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ADDemployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADDemployeeActionPerformed
        // TODO add your handling code here:
        
        FTE theFTE;
        PTE thePTE;
        
        AddEmployeeJFrame openNewWindow = new AddEmployeeJFrame();
        openNewWindow.setVisible(true);
        MyHashTable refVal = getTheHT();
        openNewWindow.setMainHT(refVal);  

       /* theFTE = new FTE(111111, "Elmer", "Fudd", 0, 3, 0.2, 80000.00);
        theHT.addEmployee(theFTE);
        System.out.println("Added the FTE to the hash table!");
                
        thePTE = new PTE(222222, "Daffy", "Duck", 0, 2, 0.22, 10.0, 20.0, 30.0);
        theHT.addEmployee(thePTE);
        System.out.println("Added the PTE to the hash table!");
                
        theFTE = new FTE(333333, "Lola", "Bunny", 1, 5, 0.17, 90000.00);
        theHT.addEmployee(theFTE);
        System.out.println("Added the FTE to the hash table!");
        */
    }//GEN-LAST:event_ADDemployeeActionPerformed

    private void SeperateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeperateActionPerformed
        // TODO add your handling code here:
        
        SeparateJFrame theSeparateJFrame = new SeparateJFrame();
        theSeparateJFrame.setVisible(true);
        MyHashTable refVal = getTheHT();
        theSeparateJFrame.setMainHT(refVal);  // Have theSeparateJFrame mainHT point to the real HT.
    }//GEN-LAST:event_SeperateActionPerformed

    private void DisplayEmployeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayEmployeesActionPerformed
        // TODO add your handling code here:
        
        DisplayEmployeesJFrame openNewWindow2 = new DisplayEmployeesJFrame();
        openNewWindow2.setVisible(true);
        MyHashTable refVal = getTheHT();
        openNewWindow2.setMainHT(refVal);
        
        
    }//GEN-LAST:event_DisplayEmployeesActionPerformed
    
   
    private void SAVEbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAVEbuttonActionPerformed
        // TODO add your handling code here:
     
     File file = new File("EMPDATA.txt");
        
            try { 
            FileWriter myWriter = new FileWriter(file);
            for (int i = 0; i < theHT.buckets.length; i++) {
                for (int j = 0; j < theHT.buckets[i].size(); j++) {
                    EmployeeInfo theEmp = theHT.buckets[i].get(j);
                    
                    if(theEmp instanceof PTE){
                        PTE thePTE = (PTE) theHT.buckets[i].get(j);
                        //PTE theEmpPTE = new PTE (empVal,fName,lName,rateValue,Hwage,hours,weeks) ;
                    //    myWriter.write("\n");
                        myWriter.write("PTE    (" + Integer.toString(theEmp.getEmpNum()) +", "+ theEmp.getFirstName() + ", " +  theEmp.getLastName() + ", " + Double.toString(theEmp.deductRate) + ", " + Double.toString(thePTE.hourlyWage) + ", " + Double.toString(thePTE.hoursPerWeek) + ", " + Double.toString(thePTE.weeksPerYear) + ")\n");
                    //    myWriter.write("\n");
                    //    System.out.println("Successfully wrote PTE to the file!");
                    }
                    
                    else{
                    if (theEmp instanceof FTE){
                        FTE theFTE = (FTE) theHT.buckets[i].get(j);
                        //FTE theEmpFTE = new FTE (empVal,fName,lName,rateValue,salary);
                    //    myWriter.write("\n");
                        myWriter.write("FTE    (" + Integer.toString(theEmp.getEmpNum()) +", "+ theEmp.getFirstName() + ", " +  theEmp.getLastName() + ", " + Double.toString(theEmp.deductRate) + ", " + Double.toString(theFTE.yearlySalary)+ ")\n") ;
                    //    myWriter.write ("\n");
                    //    System.out.println("Successfully wrote FTE to the file!");
                    }
                    }
                }
            }
            myWriter.close();
        
            }   
            catch (IOException e) {
            System.out.println("AN error occured");
        }            
   
    }//GEN-LAST:event_SAVEbuttonActionPerformed

    
    
    private void LOADbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOADbuttonActionPerformed
        // TODO add your handling code here:

        
        try {
             
            File readFile = new File("EMPDATA.txt");
            Scanner myReader = new Scanner(readFile);
            
            //We are reading the contents of the file line by line
            while (myReader.hasNextLine()) {
            String lineData = myReader.nextLine();
            System.out.println(lineData);
            
            String [] parts;
            String partsLine;
            
            //We are adding the employee to the hashtable based on whether they're an FTE or PTE
            //We're doing this by reading the first 3 characters of the line, if it is equal to FTE, we add that employee as a FTE
            //If it is equal to PTE, we add the employee as a PTE.
            //This is done because FTE and PTE have a different number of attributes and therefore slightly different ways of adding them to 
            //the hashtable/database.
            
            //In this case, the employee is an FTE
            if (lineData.substring(0,3).equals("FTE")){
            
            //    System.out.println(lineData.length());
                int lineLength = lineData.length()-1;
                partsLine = lineData.substring(8,lineLength);
                System.out.println(partsLine);
                
                parts = partsLine.split(", ");
                String empNum = parts[0];
                String fName = parts[1];
                String lName = parts[2];
                String deductRate = parts[3];
                String ySalary = parts[4];
                
                int eN = Integer.parseInt(empNum);
                double dR = Double.parseDouble(deductRate);
                double yS = Double.parseDouble(ySalary);
                
                FTE theFTE = new FTE (eN,fName,lName,dR,yS);
                theHT.addEmployee(theFTE); //adding the employee to the hashtable
                
            }
        
            if (lineData.substring(0,3).equals("PTE")){
                
            //    System.out.println(lineData.length());
                int lineLength = lineData.length()-1;
                partsLine = lineData.substring(8,lineLength);
                System.out.println(partsLine);

                    parts = partsLine.split(", ");
                String empNum = parts[0];
                String fName = parts[1];
                String lName = parts[2];
                String deductRate = parts[3];
                String hourWage = parts[4];
                String hoursWeek = parts[5];
                String wPerYear = parts[6];
                
                int eN = Integer.parseInt(empNum);
                double dR = Double.parseDouble(deductRate);
                double hW = Double.parseDouble(hourWage);
                double hPW = Double.parseDouble(hoursWeek);
                double wPY = Double.parseDouble(wPerYear);
                
                PTE thePTE = new PTE (eN,fName,lName,dR,hW,hPW,wPY) ;
                theHT.addEmployee(thePTE);  //adding the employee to the hashtable   
                
            }
            
            }
            
        myReader.close();
      } catch (FileNotFoundException e) {
        System.out.println("An error occurred.");
       }

        LOADbutton.setEnabled(false);
    }//GEN-LAST:event_LOADbuttonActionPerformed

    private void REMOVEemployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REMOVEemployeeActionPerformed
        // TODO add your handling code here:
        //Opens the new RemoveEmployeeJFrame window to remove the employee
        RemoveEmployeeJFrame openNewWindow3 = new RemoveEmployeeJFrame();
        openNewWindow3.setVisible(true);
        MyHashTable refVal = getTheHT();
        openNewWindow3.setMainHT(refVal);
        
    }//GEN-LAST:event_REMOVEemployeeActionPerformed

    private void EDITbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EDITbuttonActionPerformed
        // TODO add your handling code here:
        EditEmpJFrame openNewWindow4 = new EditEmpJFrame();
        openNewWindow4.setVisible(true);
        MyHashTable refVal = getTheHT();
        openNewWindow4.setMainHT(refVal);
    }//GEN-LAST:event_EDITbuttonActionPerformed

    private void GETINFObuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GETINFObuttonActionPerformed
        // TODO add your handling code here:
        
        GetInfo openNewWindow6 = new GetInfo();
        openNewWindow6.setVisible(true);
        MyHashTable refVal = getTheHT();
        openNewWindow6.setMainHT(refVal);
    }//GEN-LAST:event_GETINFObuttonActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADDemployee;
    private javax.swing.JButton DisplayEmployees;
    private javax.swing.JButton EDITbutton;
    private javax.swing.JButton GETINFObutton;
    private javax.swing.JButton LOADbutton;
    private javax.swing.JLabel MainTitle;
    private javax.swing.JButton REMOVEemployee;
    private javax.swing.JButton SAVEbutton;
    private javax.swing.JButton Seperate;
    // End of variables declaration//GEN-END:variables
}
